proj_name: RedPanda16S
raw_data: /home/centos/USS/cew-redpanda/16S/raw_reads_only
scratch:  /home/centos/USS/cew-redpanda/16S/SMWorkingDirectory
outputDIR: /home/centos/USS/cew-redpanda/16S/SMWorkingDirectory
manifest: /home/centos/USS/cew-redpanda/16S/manifest
manifest-trimmed: manifest-trimmed.txt
metadata: /home/centos/USS/cew-redpanda/16S/RedPandaMetadataValidated.tsv
taxonomy_db: /home/centos/USS/Bioinfotools_USS/QIIME2/silva-138-99-nb-classifier.qza

# Fastq file suffix, following the read pair designation
# suffix: .fastq.gz
suffix: _001.fastq.gz

# Read pair designations
#r1_suf: 1
#r2_suf: 2
r1_suf: R1
r2_suf: R2

# QIIME2-specific flags
# Defaults for amplicon tag-sequencing - uncomment only parameters you need.


## 16S default (Parada et al. modified EMP primers)
#primerF: GTGYCAGCMGCCGCGGTAA
#primerR: GGACTACNVGGGTWTCTAAT
# Parada et al. 2016 MEP primers for 16S
#primer_err: 0.1
#primer_overlap: 3
# Merging reads for 16S
#minoverlap: 20
#maxdiff: 4
#minlength: 200


## DADA2 - ASV flags
truncation_err: 2
truncation_len-f: 240
truncation_len-r: 220
trim_len-r: 25
trim_len-f: 25
quality_err: 2
training: 1000 #should be set higher for a non-test dataset
chimera: pooled
thread_num: 0

## taxonomy assignment
n_jobs: -2

## rarefaction depths
rarefaction_depth: 1000 # put number here

## exclude params
taxa_exclude: mitochondria,chloroplast
phy_prefix: D_1__
